(* This file was generated by Ocsigen Start.
   Feel free to use it, modify it, and redistribute it as you wish. *)

[%%shared open Eliom_content.Html.F]

(** This module defines the drawer menu *)

let%shared item text service =
  li [a ~a:[a_class ["os-drawer-item"]] ~service [txt text] ()]

let%shared make ?user:_ () =
  let items =
    [ item "Creets" H42n42_services.creets_service ]
  in
  let menu = ul ~a:[a_class ["os-drawer-menu"]] items in
  let contents = [menu] in
  let drawer, _, _ = Ot_drawer.drawer contents in
  drawer
