(* This file was generated by Ocsigen Start.
   Feel free to use it, modify it, and redistribute it as you wish. *)



let%shared () =
  (* Redirect main service to creets page *)
  H42n42_base.App.register ~service:Os_services.main_service
    (H42n42_page.Opt.connected_page H42n42_handlers.creets_handler);
  H42n42_base.App.register ~service:H42n42_services.creets_service
    (H42n42_page.Opt.connected_page H42n42_handlers.creets_handler)



(* Print more debugging information when <debugmode/> is in config file
   (DEBUG = yes in Makefile.options).
   Example of use:
   let section = Lwt_log.Section.make "H42n42:sectionname"
   ...
   Lwt_log.ign_info ~section "This is an information";
   (or ign_debug, ign_warning, ign_error etc.)
*)
let%server _ =
  if Eliom_config.get_debugmode ()
  then (
    ignore
      [%client
        ((* Eliom_config.debug_timings := true; *)
         (* Lwt_log_core.add_rule "eliom:client*" Lwt_log_js.Debug; *)
         (* Lwt_log_core.add_rule "os*" Lwt_log_js.Debug; *)
         Lwt_log_core.add_rule "H42n42*" Lwt_log_js.Debug
         (* Lwt_log_core.add_rule "*" Lwt_log_js.Debug *)
         : unit)];
    (* Lwt_log_core.add_rule "*" Lwt_log.Debug *)
    Lwt_log_core.add_rule "H42n42*" Lwt_log.Debug)

(* The modules below are all the modules that needs to be explicitely
   linked-in. *)

[%%shared.start]

(* The modules below are all the modules that needs to be explicitely
   linked-in. *)

[%%client.start]

(* Client-side only modules *)
